=head1 NAME

irc-list2rss - PSGI app to show /list as RSS feed

=head1 DESCRIPTION

This works for enumerating all channels on our (very small) local IRC
server.  It is not suitable for pointing at a public server.

This code is abandonware.  It works for me, you're welcome to hack on
it.

=head1 AUTHOR

Copyright (c) 2012 Matthew Astley

All rights reserved. This program is free software; you can
redistribute it and/or modify it under the same terms as Perl itself.

=cut
